name: angel_site
publish_to: none
dependencies:
    angular2: ^2.2.0
    angular2_components: 
    barback: ^0.15.2
    js: ^0.6.1
    material_menu: ^1.0.0
    material_toolbar: ^1.0.0
    material_sidenav: ^1.0.0
    ng_mediaquery: ^0.1.3
    stylus: ^0.1.1
dev_dependencies:
    browser: ^0.10.0
    dart_to_js_script_rewriter: ^1.0.0
transformers:
- dart_to_js_script_rewriter
- angel_site/stylus
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart